name: Report a bug
description: Something wrong? Let us know.
title: '[BUG]'
labels: ["bug"]
assignees: 'FabWishlist'
body:
  - type: markdown
    attributes:
      value: |
        ![alt text](https://i.imgur.com/C0jN92e.png) 
        #
        Thank you for helping us improve the Fab Wishlist experience! If you've encountered a bug or issue while using the Wishlist feature, please provide as many details as possible to help our team investigate and resolve the problem quickly. Please fill out the form below
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      placeholder: (Please describe the desired behavior or feature you were expecting.)
  - type: textarea
    id: actual-behavior
    attributes:
      label: What actually happened?
      placeholder: (Please provide a detailed description of the issue, including any error messages or unexpected behavior.)
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        (Please list the steps you took that led to the bug, so we can reproduce it on our end.)
        1.
        2.
        3.
        4.
        (Include any specific actions, buttons, or screens involved.)
  - type: checkboxes
    id: Frequency
    attributes:
      label: Frequency of the Issue
      description: 
      options:
        - label: Always
        - label: Sometimes
        - label: Rarely
        - label: Occasionally
  - type: dropdown
    id: Device
    attributes:
      label: Device & Environment Information
      description: Please select your device type.
      options:
        - "Desktop"
        - "Mobile"
        - "Tablet"
  - type: dropdown
    id: System
    attributes:
      label: Operating System
      description: Please select your operating system.
      options:
        - "Windows"
        - "macOS"
        - "iOS"
        - "Android"
        - "Other: _______"
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: markdown
    attributes:
      value: |
        #
        ![alt text](https://i.imgur.com/gPLIPjL.png)
 
