name: Have a Question
description: I'm here to help you personally!
title: "[Question]"
labels: ["question"]
assignees: "FabWishlist"
body:
  - type: markdown
    attributes:
      value: |
        ![alt text](https://i.imgur.com/C0jN92e.png)
        #
        Have a question or need clarification? We're here to help! Submit your question below and we'll get back to you as soon as possible:
    validations:
      required: true
  - type: textarea
    id: question-summary
    attributes:
      label: Question Summary
      placeholder: (Provide a brief summary of your question or topic.)
    validations:
      required: true
  - type: textarea
    id: question-details
    attributes:
      label: Details of Your Question
      placeholder: (Please provide detailed information or context to help us better understand your question.)
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency Level
      description: How soon do you need an answer?
      options:
        - "Urgent"
        - "Soon"
        - "Whenever possible"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        #
        ![alt text](https://i.imgur.com/smUG8R5.png)
