name: Bug Report
description: File a bug/issue
title: '[BUG] <title>'
labels: ["bug"]
assignees: 'FabWishlist'
body:
  - type: markdown
    attributes:
      value: |
        ![alt text](https://i.imgur.com/C0jN92e.png) 
        #
        Thank you for helping us improve the Fab Wishlist experience! If you've encountered a bug or issue while using the Wishlist feature, please provide as many details as possible to help our team investigate and resolve the problem quickly. Please fill out the form below
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      placeholder: (Please describe the desired behavior or feature you were expecting.)
  - type: textarea
    id: actual-behavior
    attributes:
      label: What actually happened?
      placeholder: (Please provide a detailed description of the issue, including any error messages or unexpected behavior.)
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        (Please list the steps you took that led to the bug, so we can reproduce it on our end.)
        1.
        2.
        3.
        4.
        (Include any specific actions, buttons, or screens involved.)
  - type: checkboxes
    id: Frequency
    attributes:
      label: Frequency of the Issue
      options:
        - label: Always
        - label: Sometimes
        - label: Rarely
        - label: Occasionally
  - type: checkboxes
    id: Device
    attributes:
      label: Device & Environment Information
      description: Device Type:
      options:
        - label: Desktop
        - label: Mobile
        - label: Tablet
  - type: textarea
    id: expected-result
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
        - "No"
  - type: markdown
    attributes:
      value: |
        #
        ![alt text](https://i.imgur.com/gPLIPjL.png)
