name: Bug Report
description: File a bug/issue
title: '[BUG] <title>'
labels: ["bug"]
assignees: 'FabWishlist'
body:
  - type: markdown
    attributes:
      value: |
        ![alt text](https://i.imgur.com/C0jN92e.png) 
        #
         w
    id: description
    attributes:
      label: What did you expect to happen?
      placeholder: (Please describe the desired behavior or feature you were expecting.)
   validations:
    required: true
  - type: textarea
    id: description
    attributes:
      label: What actually happened?
      placeholder: (Please provide a detailed description of the issue, including any error messages or unexpected behavior.)
   required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        (Please list the steps you took that led to the bug, so we can reproduce it on our end.)
        1.
        2.
        3.
        4.
        (Include any specific actions, buttons, or screens involved.)
      validations:
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: Always
        - label: Often
        - label: Occasionally
        - label: Rarely
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
  - type: markdown
    attributes:
      value: |
        #
        ![alt text](https://i.imgur.com/gPLIPjL.png)
