name: Sync Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels/labels.yml

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Sync Labels
        uses: robinpowered/github-labels@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels/labels.yml
